import Head from 'next/head'
import { Inter } from '@next/font/google'
import myky from '../public/myky.jpeg';
import Image from "next/legacy/image";
import {AiFillInstagram, AiFillLinkedin} from 'react-icons/ai'
import Instagram from './components/Instagram';
import hair1 from '../public/hair1.jpg';
import hair2 from '../public/hair2.jpg';
import hair3 from '../public/hair3.jpg';
import hair4 from '../public/hair4.jpg';
import hair5 from '../public/hair5.jpg';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
      <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet"/>
        <title>Myky's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-5'>

        <section className='min-h-screen font-Cinzel'>

          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-gray-900 text-xl pr-5'>ColorByMyky</h1>
            <ul className='flex items-center'>
              <a href='#about'><li className='text-gray-900 hover:text-pink-400  text-xl'>About</li></a>
              <a href='#contact'><li className='text-gray-900 px-4 ml-8 hover:text-pink-400 text-xl'>Contact</li></a>
            </ul>
          </nav>


          <div className='flex justify-center items-center' id='about'>
            <div className='text-center max-w-sm mr-3'>
              <h2 className='text-xl'>Myky Do</h2>
              <h3 className='text-l'>Hairstylist</h3>
              <p className='leading-8 text-sm'>
                New Hairstylist specializing in color!
                New Hairstylist specializing in color!
                New Hairstylist specializing in color!
                New Hairstylist specializing in color!
              </p>
            </div>
            <div className=''>
              <Image src={myky} className="rounded-lg" width={420} height={550}/>
            </div>
          </div>

          <div className='flex justify-center items-center mt-12 text-gray-700 leading-8' >

            <div className='text-center max-w-lg'>

              <h3 className='text-l'>Welcome to my portfolio!</h3>
              <h1 className='text-3xl'>Color Specialist</h1>
              <p className='text-md'>Myky Do is a Color hair specialist currently located in Sacramento, California.
              Having her diploma from Federicos Beauty Institute.
              </p>

            </div>
            
          </div>

          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            
            <div className='basis-1/6 flex-1'>
              <Image src={hair1} className='rounded-lg object-cover' style={{width:'100%' , height:'100%'}} layout='responsive'/>
            </div>

            <div className='basis-1/6 flex-1'>
              <Image src={hair2} className='rounded-lg object-cover' style={{width:'100%' , height:'100%'}} layout='responsive'/>
            </div>

            <div className='basis-1/6 flex-1'>
              <Image src={hair3} className='rounded-lg object-cover' style={{width:'100%' , height:'100%'}} layout='responsive'/>
            </div>

            <div className='basis-1/6 flex-1'>
              <Image src={hair4} className='rounded-lg object-cover' style={{width:'100%' , height:'100%'}} layout='responsive'/>
            </div>

            <div className='basis-1/6 flex-1'>
              <Image src={hair5} className='rounded-lg object-cover' style={{width:'100%' , height:'100%'}} layout='responsive'/>
            </div>

   

          </div>

          <div className='flex justify-center text-7xl text-pink-300 mt-10'>
            <a href="https://www.instagram.com/colorbymyky/?hl=en" target="_blank">
              <AiFillInstagram/>
            </a>

          </div>


          <h1 className='w-full flex justify-center mt-10' id='contact'>Contact me</h1>
          <form className='flex justify-center my-4' action='https://mailthis.to/giahuyg08@gmail.com' method='POST'>
            <div>

                <input type='text' name='name' className='shadow-lg shadow-pink-300 w-1/2 text-center h-10' placeholder='Your Name'/>


                <input type='text' name='name' className='shadow-lg shadow-pink-300 w-1/2 text-center h-10' placeholder='Email'/>


                <input type='text' name='name' className='shadow-lg shadow-pink-300 w-full text-center h-10' placeholder='About inaquiry'/>


                <input type='submit' value='send' className='w-full text-center hover:text-pink-600 mt-5 text-xl'/>
            </div>
            
          </form>


        </section>
      </main>
    </>
  )
}
